experiment_name: "experiment"
hydra:
  run:
    dir: ./outputs/${now:%Y-%m-%d}_${now:%H-%M-%S}_${experiment_name}
  job:
    chdir: True
train:
  dataset:
    path: "/home/peter/PycharmProjects/transformers/language_prediction/input.txt"
    split: [0.0, 0.9]
    seq_len: 256
  loader:
    num_workers: 1
    batch_size: 64
    shuffle: True
val:
  dataset:
    path: "/home/peter/PycharmProjects/transformers/language_prediction/input.txt"
    split: [0.9, 1.0]
    seq_len: 256
  loader:
    num_workers: 0
    batch_size: 1
    shuffle: False
device: "cuda:0"
max_iters: 20000
eval_interval: 500
lr: 3e-4
module: models.karpathy_official_mha  # official, third_party, karpathy, karpathy_parallel, karpathy_official_mha, einops
model: GPT
model_args:
  d_model: 384
  seq_len: 256
  dropout: 0.2
  h: 6
  n: 6
  d_ff: 1536
